name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Check code style
        run: |
          npm run prettier
          npm run lint

      - name: Create .env file
        run: echo "${{ secrets.ENV_FILE }}" > .env

      - name: Run tests
        run: npm run test

      - name: Build
        run: npm run build
