name: Docker Image CI

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

env:
  DOCKER_IMAGE: ${{ vars.REGISTRY }}/${{ vars.PROJECT_NAME }}:${{ vars.VERSION }}

jobs:
  buildandpush:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Create env file
        run: echo "${{ secrets.ENV_PRODUCTION }}" > .env.production
      - name: Build the Docker image
        run: docker build -t $DOCKER_IMAGE .
      - name: Login to Docker Hub
        run: docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Push the Docker image
        run: docker push $DOCKER_IMAGE
